import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavButtons from "@/app/components/NavButtons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-w-screen min-h-screen`}>
        <div className="bg-[#FEFEFE0D] h-16"></div>
        <div className="grid grid-cols-[49px_1fr]">
          <div className="w-16 h-[calc(100vh-49px)] bg-[#FEFEFE08]">
            <NavButtons />
          </div>
          <div className="">{children}</div>
        </div>
      </body>
    </html>
  );
}
